language: go

go:
  - 1.4.2
  - 1.5.2

install:
    - go get github.com/tools/godep
    - go get github.com/golang/lint/golint
    - go get github.com/GeertJohan/fgt

script: fgt golint ./... && godep go test ./...
